apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-eno1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-eno1@sha256:cbf44d8cff9d772ad78c99afd30b587f00577479e8c54d148e886d8c7824841c
        name: my-nodejs
        resources: {}
status: {}
